Vagrant.configure("2") do |config|


  config.vm.define "debian-vm" do |debian|
    debian.vm.box = "debian/bullseye64"
    debian.vm.provision "shell", inline: <<-SHELL
      echo  "Ciao! Digita moon-buggy per iniziare a giocare!" >> /home/vagrant/.bashrc
    SHELL

    debian.vm.box_check_update = true
    debian.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
    end

    debian.vm.provider "virtualbox" do |vb|
      vb.name = "debian-vm"  
      vb.gui = false
      vb.memory = "5024"
    end
  end

end

