Vagrant.configure("2") do |config| 
  config.vm.define "debian-track6-node" do |debian|
  config.vm.network "forwarded_port" , host: 3000 , guest: 3000
  config.vm.network "forwarded_port" , host: 5000 , guest: 5000
  config.vm.network "forwarded_port" , host: 9090 , guest: 9090
  config.vm.network "forwarded_port" , host: 9464 , guest: 9464
  config.vm.network "forwarded_port" , host: 4317 , guest: 4317
  config.vm.network "forwarded_port" , host: 4318 , guest: 4318



    debian.vm.box = "debian/bookworm64"
    debian.vm.synced_folder "./otel-lab", "/home/vagrant/otel-lab"
    debian.vm.synced_folder "./flask_service", "/home/vagrant/flask_service"


    debian.vm.provider "virtualbox" do |virtual| 
      virtual.gui = false
      virtual.name = "debian-track"
      virtual.memory = 5024
    end

    debian.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install -y podman podman-compose
      sudo apt install -y curl 
      cd otel-lab
      sudo podman-compose up -d
    SHELL

  end
end
