services:
  python-app:
    build: 
      context:
          ../flask_service
      dockerfile: Dockerfile
    container_name: python-app
    ports:
      - "5000:5000"
    networks:
      - otel-network

  otel-collector:
    image: docker.io/otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" 
      - "4318:4318" 
      - "9464:9464" 

    networks:
      - otel-network

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    networks:
      - otel-network

  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - otel-network
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana


networks:
   otel-network:
       driver: bridge

volumes:
   grafana_data:
   prometheus_data: