Vagrant.configure("2") do |config| 

    config.vm.define "debian-node" do |debian|
        debian.vm.box = "debian/bookworm64"
        debian.vm.provider "virtualbox" do |v| 
            v.gui=false
            v.name="debian-forjinja-vm"
            v.memory= "5024"
        end 

        debian.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo apt install -y python3-pip python3-venv
        python3 -m venv /home/vagrant/venv
        sudo apt install curl
        sudo apt update
        sudo apt install -y apt-transport-https ca-certificates curl gnupg
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg 
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
        sudo chmod 644 /etc/apt/sources.list.d/kubernetes.list  
        sudo apt update 
        sudo apt install kubectl -y
        SHELL
                
        debian.vm.provision "ansible" do |ansible| 
            ansible.playbook = "playbooks/jinja-injector-playbook.yaml"
            ansible.playbook = "playbooks/allow-users.playbook.yaml"
            ansible.playbook = "playbooks/apache-playbook.yaml"
        end
    end

end