Vagrant.configure("2") do |config| 

    config.vm.define "debian-node" do |debian|
        debian.vm.box = "debian/bookworm64"
        debian.vm.provider "virtualbox" do |v| 
            v.gui=false
            v.name="debian-forjinja-vm"
            v.memory= "5024"
        end 

        debian.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo apt install -y python3-pip python3-venv
        python3 -m venv /home/vagrant/venv
      
        SHELL
                
        debian.vm.provision "ansible" do |ansible| 
            ansible.playbook = "playbooks/jinja-injector-playbook.yaml"
            ansible.playbook = "playbooks/allow-users.playbook.yaml"
            ansible.playbook = "playbooks/apache-playbook.yaml"
        end
    end

end