- hosts: debian-node
  gather_facts: false
  become: true 
  vars:
     server_name: www.example.com
     document_root: /var/www/example

  tasks:

    - name: Installa Apache2
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Avvia Apache2
      ansible.builtin.systemd:
        name: apache2
        state: started

    - name: Genera file Apache Virtual Host da template
      template:
        src: ../templates/hostconf.j2
        dest: "/etc/apache2/sites-available/{{ server_name }}.conf"
      when: server_name is defined
