Vagrant.configure("2") do |config|
    

    config.vm.define "ubuntu-node" do |ubuntu|
      ubuntu.vm.box = "ubuntu/jammy64" 
      ubuntu.vm.hostname = "ubuntu"

      ubuntu.vm.provision "shell", inline: <<-SHELL
        apt-get update -y
        apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update -y
        apt-get install -y docker-ce docker-ce-cli containerd.io
        sudo usermod -aG docker vagrant
        docker pull ealen/echo-server
      SHELL
      
    end

    config.vm.define "debian-node" do |debian|
      debian.vm.box = "debian/bullseye64" 
      debian.vm.hostname = "debian"

      debian.vm.provision "shell", inline: <<-SHELL
        apt-get update -y
        apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update -y
        apt-get install -y docker-ce docker-ce-cli containerd.io
        sudo usermod -aG docker vagrant
        docker pull ealen/echo-server
      SHELL

    end

end 
  


